version: "3"

services:
  nuxt:
    build: .
    restart: always
    network_mode: host
    ports:
      - 3000:3000
    command:
      "yarn start"
    environment:
      - CTF_SPACE_ID=${CTF_SPACE_ID}
      - CTF_ACCESS_TOKEN=${CTF_ACCESS_TOKEN}
    # volumes:
    #   - ./Nuxt/:/app
    #   - /app/node_modules
